// <auto-generated />
using System;
using MediLogic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediLogic.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260422163849_AddPaymentMethodToSales")]
    partial class AddPaymentMethodToSales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediLogic.Models.AssignRole", b =>
                {
                    b.Property<int>("AssignRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignRoleId"));

                    b.Property<DateTime?>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AssignRoleId")
                        .HasName("PK__AssignRo__1BFA36ED90FCDC73");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("AssignRole", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.BatchStock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockId"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("Mrp")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("StockId")
                        .HasName("PK__BatchSto__2C83A9C2E2988BA6");

                    b.HasIndex("BranchId");

                    b.HasIndex("ProductId");

                    b.ToTable("BatchStock", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<DateTime?>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("BranchId")
                        .HasName("PK__Branch__A1682FC5E1FC5723");

                    b.HasIndex("CompanyId");

                    b.ToTable("Branch", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__19093A0BD7CBA2D9");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CompanyId")
                        .HasName("PK__Company__2D971CAC68F1D077");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.Ledger", b =>
                {
                    b.Property<int>("LedgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LedgerId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PartyId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LedgerId")
                        .HasName("PK__Ledger__3214EC07");

                    b.HasIndex("BranchId");

                    b.HasIndex("PartyId");

                    b.ToTable("Ledger", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartyId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("CreditBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("CurrentBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PartyCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PartyId")
                        .HasName("PK__Party__1640CD336C264D8D");

                    b.HasIndex("BranchId");

                    b.ToTable("Party", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("GenericName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ProductCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Strength")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TaxId")
                        .HasColumnType("int");

                    b.Property<int?>("UomId")
                        .HasColumnType("int");

                    b.HasKey("ProductId")
                        .HasName("PK__Product__B40CC6CDC9D6A7C6");

                    b.HasIndex("BranchId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TaxId");

                    b.HasIndex("UomId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.ProductMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("OpeningDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("OpeningQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("OpeningValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ProductM__3214EC07BC4DF48E");

                    b.HasIndex("BranchId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMaster", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.PurchaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ReturnedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Purchase__3214EC07E08C2096");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseDetail", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.PurchaseMaster", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PurchaseNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PurchaseId")
                        .HasName("PK__Purchase__6B0A6BBE6DDA33B8");

                    b.HasIndex("BranchId");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseMaster", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.PurchaseReturnDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseReturnId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Purchase__3214EC07142FF02F");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseReturnId");

                    b.ToTable("PurchaseReturnDetail", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.PurchaseReturnMaster", b =>
                {
                    b.Property<int>("PurchaseReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseReturnId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ReturnNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalReturnAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PurchaseReturnId")
                        .HasName("PK__Purchase__2C33C6E885AB0107");

                    b.HasIndex("BranchId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseReturnMaster", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE1A268FF442");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.SalesDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PurchasePriceAtTime")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ReturnedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("SalesId")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("DetailId")
                        .HasName("PK__SalesDet__135C316D2C5BA50E");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesId");

                    b.ToTable("SalesDetail", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.SalesMaster", b =>
                {
                    b.Property<int>("SalesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("NetAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("PartyId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SalesDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SalesId")
                        .HasName("PK__SalesMas__C952FB32D57AA681");

                    b.HasIndex("BranchId");

                    b.HasIndex("PartyId");

                    b.HasIndex("UserId");

                    b.ToTable("SalesMaster", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.SalesReturnDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("SalesReturnId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__SalesRet__3214EC07B33CC08D");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesReturnId");

                    b.ToTable("SalesReturnDetail", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.SalesReturnMaster", b =>
                {
                    b.Property<int>("SalesReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesReturnId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ReturnNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SalesId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalRefundAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("SalesReturnId")
                        .HasName("PK__SalesRet__E0906C38A4E7D075");

                    b.HasIndex("BranchId");

                    b.HasIndex("SalesId");

                    b.ToTable("SalesReturnMaster", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.Tax", b =>
                {
                    b.Property<int>("TaxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxId"));

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("VatRate")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("TaxId")
                        .HasName("PK__Tax__711BE0AC39DFDB5F");

                    b.ToTable("Tax", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.Uom", b =>
                {
                    b.Property<int>("UomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UomId"));

                    b.Property<string>("UomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UomId")
                        .HasName("PK__Uom__F6F8D47E5FEDF8B5");

                    b.ToTable("Uom", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4C842C4899");

                    b.HasIndex("BranchId");

                    b.HasIndex(new[] { "UserName" }, "UQ__User__C9F28456AD12E391")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.UserRefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime?>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TokenId")
                        .HasName("PK__UserRefr__658FEEEA41C5CF7D");

                    b.HasIndex("UserId");

                    b.ToTable("UserRefreshToken", (string)null);
                });

            modelBuilder.Entity("MediLogic.Models.AssignRole", b =>
                {
                    b.HasOne("MediLogic.Models.Role", "Role")
                        .WithMany("AssignRoles")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__AssignRol__RoleI__18EBB532");

                    b.HasOne("MediLogic.Models.User", "User")
                        .WithMany("AssignRoles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__AssignRol__UserI__17F790F9");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediLogic.Models.BatchStock", b =>
                {
                    b.HasOne("MediLogic.Models.Branch", "Branch")
                        .WithMany("BatchStocks")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK__BatchStoc__Branc__10566F31");

                    b.HasOne("MediLogic.Models.Product", "Product")
                        .WithMany("BatchStocks")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__BatchStoc__Produ__0F624AF8");

                    b.Navigation("Branch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MediLogic.Models.Branch", b =>
                {
                    b.HasOne("MediLogic.Models.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK__Branch__CompanyI__4CA06362");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MediLogic.Models.Ledger", b =>
                {
                    b.HasOne("MediLogic.Models.Branch", "Branch")
                        .WithMany("Ledgers")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK__Ledger__BranchId__1DB06A4G");

                    b.HasOne("MediLogic.Models.Party", "Party")
                        .WithMany("Ledgers")
                        .HasForeignKey("PartyId")
                        .HasConstraintName("FK__Ledger__PartyId__1DB06A4H");

                    b.Navigation("Branch");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("MediLogic.Models.Party", b =>
                {
                    b.HasOne("MediLogic.Models.Branch", "Branch")
                        .WithMany("Parties")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK__Party__BranchId__656C112C");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("MediLogic.Models.Product", b =>
                {
                    b.HasOne("MediLogic.Models.Branch", "Branch")
                        .WithMany("Products")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK__Product__BranchId");

                    b.HasOne("MediLogic.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Product__Categor__59063A47");

                    b.HasOne("MediLogic.Models.Tax", "Tax")
                        .WithMany("Products")
                        .HasForeignKey("TaxId")
                        .HasConstraintName("FK__Product__TaxId__5AEE82B9");

                    b.HasOne("MediLogic.Models.Uom", "Uom")
                        .WithMany("Products")
                        .HasForeignKey("UomId")
                        .HasConstraintName("FK__Product__UomId__59FA5E80");

                    b.Navigation("Branch");

                    b.Navigation("Category");

                    b.Navigation("Tax");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("MediLogic.Models.ProductMaster", b =>
                {
                    b.HasOne("MediLogic.Models.Branch", "Branch")
                        .WithMany("ProductMasters")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK__ProductMa__Branc__151B244E");

                    b.HasOne("MediLogic.Models.Product", "Product")
                        .WithMany("ProductMasters")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__ProductMa__Produ__14270015");

                    b.Navigation("Branch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MediLogic.Models.PurchaseDetail", b =>
                {
                    b.HasOne("MediLogic.Models.Product", "Product")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__PurchaseD__Produ__70DDC3D8");

                    b.HasOne("MediLogic.Models.PurchaseMaster", "Purchase")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("FK__PurchaseD__Purch__6FE99F9F");

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("MediLogic.Models.PurchaseMaster", b =>
                {
                    b.HasOne("MediLogic.Models.Branch", "Branch")
                        .WithMany("PurchaseMasters")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK__PurchaseM__Branc__6C190EBB");

                    b.HasOne("MediLogic.Models.Party", "Supplier")
                        .WithMany("PurchaseMasters")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK__PurchaseM__Suppl__6B24EA82");

                    b.Navigation("Branch");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MediLogic.Models.PurchaseReturnDetail", b =>
                {
                    b.HasOne("MediLogic.Models.Product", "Product")
                        .WithMany("PurchaseReturnDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__PurchaseR__Produ__0C85DE4D");

                    b.HasOne("MediLogic.Models.PurchaseReturnMaster", "PurchaseReturn")
                        .WithMany("PurchaseReturnDetails")
                        .HasForeignKey("PurchaseReturnId")
                        .HasConstraintName("FK__PurchaseR__Purch__0B91BA14");

                    b.Navigation("Product");

                    b.Navigation("PurchaseReturn");
                });

            modelBuilder.Entity("MediLogic.Models.PurchaseReturnMaster", b =>
                {
                    b.HasOne("MediLogic.Models.Branch", "Branch")
                        .WithMany("PurchaseReturnMasters")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK__PurchaseR__Branc__07C12930");

                    b.HasOne("MediLogic.Models.PurchaseMaster", "Purchase")
                        .WithMany("PurchaseReturnMasters")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("FK__PurchaseR__Purch__05D8E0BE");

                    b.HasOne("MediLogic.Models.Party", "Supplier")
                        .WithMany("PurchaseReturnMasters")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK__PurchaseR__Suppl__06CD04F7");

                    b.Navigation("Branch");

                    b.Navigation("Purchase");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MediLogic.Models.SalesDetail", b =>
                {
                    b.HasOne("MediLogic.Models.Product", "Product")
                        .WithMany("SalesDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__SalesDeta__Produ__7A672E12");

                    b.HasOne("MediLogic.Models.SalesMaster", "Sales")
                        .WithMany("SalesDetails")
                        .HasForeignKey("SalesId")
                        .HasConstraintName("FK__SalesDeta__Sales__797309D9");

                    b.Navigation("Product");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("MediLogic.Models.SalesMaster", b =>
                {
                    b.HasOne("MediLogic.Models.Branch", "Branch")
                        .WithMany("SalesMasters")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK__SalesMast__Branc__73BA3083");

                    b.HasOne("MediLogic.Models.Party", "Party")
                        .WithMany("SalesMasters")
                        .HasForeignKey("PartyId")
                        .HasConstraintName("FK__SalesMast__Party__75A278F5");

                    b.HasOne("MediLogic.Models.User", "User")
                        .WithMany("SalesMasters")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__SalesMast__UserI__74AE54BC");

                    b.Navigation("Branch");

                    b.Navigation("Party");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediLogic.Models.SalesReturnDetail", b =>
                {
                    b.HasOne("MediLogic.Models.Product", "Product")
                        .WithMany("SalesReturnDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__SalesRetu__Produ__02FC7413");

                    b.HasOne("MediLogic.Models.SalesReturnMaster", "SalesReturn")
                        .WithMany("SalesReturnDetails")
                        .HasForeignKey("SalesReturnId")
                        .HasConstraintName("FK__SalesRetu__Sales__02084FDA");

                    b.Navigation("Product");

                    b.Navigation("SalesReturn");
                });

            modelBuilder.Entity("MediLogic.Models.SalesReturnMaster", b =>
                {
                    b.HasOne("MediLogic.Models.Branch", "Branch")
                        .WithMany("SalesReturnMasters")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK__SalesRetu__Branc__7E37BEF6");

                    b.HasOne("MediLogic.Models.SalesMaster", "Sales")
                        .WithMany("SalesReturnMasters")
                        .HasForeignKey("SalesId")
                        .HasConstraintName("FK__SalesRetu__Sales__7D439ABD");

                    b.Navigation("Branch");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("MediLogic.Models.User", b =>
                {
                    b.HasOne("MediLogic.Models.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK__User__BranchId__5FB337D6");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("MediLogic.Models.UserRefreshToken", b =>
                {
                    b.HasOne("MediLogic.Models.User", "User")
                        .WithMany("UserRefreshTokens")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__UserRefre__UserI__1DB06A4F");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediLogic.Models.Branch", b =>
                {
                    b.Navigation("BatchStocks");

                    b.Navigation("Ledgers");

                    b.Navigation("Parties");

                    b.Navigation("ProductMasters");

                    b.Navigation("Products");

                    b.Navigation("PurchaseMasters");

                    b.Navigation("PurchaseReturnMasters");

                    b.Navigation("SalesMasters");

                    b.Navigation("SalesReturnMasters");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MediLogic.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MediLogic.Models.Company", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("MediLogic.Models.Party", b =>
                {
                    b.Navigation("Ledgers");

                    b.Navigation("PurchaseMasters");

                    b.Navigation("PurchaseReturnMasters");

                    b.Navigation("SalesMasters");
                });

            modelBuilder.Entity("MediLogic.Models.Product", b =>
                {
                    b.Navigation("BatchStocks");

                    b.Navigation("ProductMasters");

                    b.Navigation("PurchaseDetails");

                    b.Navigation("PurchaseReturnDetails");

                    b.Navigation("SalesDetails");

                    b.Navigation("SalesReturnDetails");
                });

            modelBuilder.Entity("MediLogic.Models.PurchaseMaster", b =>
                {
                    b.Navigation("PurchaseDetails");

                    b.Navigation("PurchaseReturnMasters");
                });

            modelBuilder.Entity("MediLogic.Models.PurchaseReturnMaster", b =>
                {
                    b.Navigation("PurchaseReturnDetails");
                });

            modelBuilder.Entity("MediLogic.Models.Role", b =>
                {
                    b.Navigation("AssignRoles");
                });

            modelBuilder.Entity("MediLogic.Models.SalesMaster", b =>
                {
                    b.Navigation("SalesDetails");

                    b.Navigation("SalesReturnMasters");
                });

            modelBuilder.Entity("MediLogic.Models.SalesReturnMaster", b =>
                {
                    b.Navigation("SalesReturnDetails");
                });

            modelBuilder.Entity("MediLogic.Models.Tax", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MediLogic.Models.Uom", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MediLogic.Models.User", b =>
                {
                    b.Navigation("AssignRoles");

                    b.Navigation("SalesMasters");

                    b.Navigation("UserRefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
